INSERT INTO `ROLE` (ID, NAME) VALUES (1,'ROLE_USER');
INSERT INTO `ROLE` (ID, NAME) VALUES (2,'ROLE_MODERATOR');
INSERT INTO `ROLE` (ID, NAME) VALUES (3,'ROLE_ADMIN');

INSERT INTO `USER` (ID, USERNAME, EMAIL, PASSWORD) VALUES (1,'GABRIEL', 'gabrielmendes17@gmail.com', '$2a$10$NtrhzERiaQ97a6t8XnombeC4r77mcOZBUHM14SmmzzraUAcZFGN.2');


INSERT INTO `USER_ROLE` (USER_ID, ROLE_ID) VALUES (1, 3);