INSERT INTO `ROLE` (NAME) VALUES ('ROLE_USER');
INSERT INTO `ROLE` (NAME) VALUES ('ROLE_MODERATOR');
INSERT INTO `ROLE` (NAME) VALUES ('ROLE_ADMIN');

INSERT INTO `USER` (USERNAME, EMAIL, PASSWORD) VALUES ('GABRIEL', 'gabrielmendes17@gmail.com', '$2a$10$NtrhzERiaQ97a6t8XnombeC4r77mcOZBUHM14SmmzzraUAcZFGN.2');
INSERT INTO `USER` (USERNAME, EMAIL, PASSWORD) VALUES ('JOAO', 'joao@gmail.com', '$2a$10$NtrhzERiaQ97a6t8XnombeC4r77mcOZBUHM14SmmzzraUAcZFGN.2');


INSERT INTO `USER_ROLE` (USER_ID, ROLE_ID) VALUES (1, 3);
INSERT INTO `USER_ROLE` (USER_ID, ROLE_ID) VALUES (2, 3);

INSERT INTO `GAME_MATCH` (CREATED_AT, FINISHED_AT, USER_ID) VALUES (CURRENT_DATE, CURRENT_DATE, 1);
INSERT INTO `GAME_MATCH` (CREATED_AT, FINISHED_AT, USER_ID) VALUES (CURRENT_DATE, CURRENT_DATE, 2);


INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (1, 1);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (1, 2);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (1, 1);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (1, 2);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (1, 1);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (1, 2);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (0, 1);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (0, 2);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (0, 1);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (0, 2);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (0, 1);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (0, 2);
INSERT INTO `GAME_ROUND` (SCORE, GAME_MATCH_ID) VALUES (0, 1);
